name: trabalho01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5 # ou a versão mais recente
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0   # caso use código gerado
  # adicione outros pacotes que você usar, como freezed ou json_serializable

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/